<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Import factor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Import factor_model');
    } 

    /*
     * Listing of import factor
     */
    function index()
    {
        $data['import factor'] = $this->Import factor_model->get_all_import factor();
        
        $data['_view'] = 'import factor/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new import factor
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'sex' => $this->input->post('sex'),
				'age' => $this->input->post('age'),
				'text' => $this->input->post('text'),
            );
            
            $import factor_id = $this->Import factor_model->add_import factor($params);
            redirect('import factor/index');
        }
        else
        {            
            $data['_view'] = 'import factor/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a import factor
     */
    function edit($Factor_id)
    {   
        // check if the import factor exists before trying to edit it
        $data['import factor'] = $this->Import factor_model->get_import factor($Factor_id);
        
        if(isset($data['import factor']['Factor_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'sex' => $this->input->post('sex'),
					'age' => $this->input->post('age'),
					'text' => $this->input->post('text'),
                );

                $this->Import factor_model->update_import factor($Factor_id,$params);            
                redirect('import factor/index');
            }
            else
            {
                $data['_view'] = 'import factor/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The import factor you are trying to edit does not exist.');
    } 

    /*
     * Deleting import factor
     */
    function remove($Factor_id)
    {
        $import factor = $this->Import factor_model->get_import factor($Factor_id);

        // check if the import factor exists before trying to delete it
        if(isset($import factor['Factor_id']))
        {
            $this->Import factor_model->delete_import factor($Factor_id);
            redirect('import factor/index');
        }
        else
            show_error('The import factor you are trying to delete does not exist.');
    }
    
}
