<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Logincontroller extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    public function index(){
        $this->load->helper('url');
        $this->load->view('loginpage');
    }
}

