<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tacking extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tacking_model');
    } 

    /*
     * Listing of tacking
     */
    function index()
    {
        $data['tacking'] = $this->Tacking_model->get_all_tacking();
        
        $data['_view'] = 'tacking/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tacking
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'app' => $this->input->post('app'),
				'time' => $this->input->post('time'),
				'date' => $this->input->post('date'),
				'status' => $this->input->post('status'),
				'Total time' => $this->input->post('Total time'),
            );
            
            $tacking_id = $this->Tacking_model->add_tacking($params);
            redirect('tacking/index');
        }
        else
        {            
            $data['_view'] = 'tacking/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tacking
     */
    function edit($tac_id)
    {   
        // check if the tacking exists before trying to edit it
        $data['tacking'] = $this->Tacking_model->get_tacking($tac_id);
        
        if(isset($data['tacking']['tac_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'app' => $this->input->post('app'),
					'time' => $this->input->post('time'),
					'date' => $this->input->post('date'),
					'status' => $this->input->post('status'),
					'Total time' => $this->input->post('Total time'),
                );

                $this->Tacking_model->update_tacking($tac_id,$params);            
                redirect('tacking/index');
            }
            else
            {
                $data['_view'] = 'tacking/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tacking you are trying to edit does not exist.');
    } 

    /*
     * Deleting tacking
     */
    function remove($tac_id)
    {
        $tacking = $this->Tacking_model->get_tacking($tac_id);

        // check if the tacking exists before trying to delete it
        if(isset($tacking['tac_id']))
        {
            $this->Tacking_model->delete_tacking($tac_id);
            redirect('tacking/index');
        }
        else
            show_error('The tacking you are trying to delete does not exist.');
    }
    
}
