<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Welcome extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->library(array('session'));
        $this->load->model(array('CI_auth', 'CI_menu'));
        
    }

    public function index(){
        $data = array('menu_top' => $this->CI_menu->menu_top(),);

        $this->load->view('welcome_message', $data);
        // $this->load->helper('url');
        // $this->load->view('loginpage');
    }
}

