<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Knowledge_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get knowledge by Know_Id
     */
    function get_knowledge($Know_Id)
    {
        return $this->db->get_where('knowledge',array('Know_Id'=>$Know_Id))->row_array();
    }
        
    /*
     * Get all knowledge
     */
    function get_all_knowledge()
    {
        $this->db->order_by('Know_Id', 'desc');
        return $this->db->get('knowledge')->result_array();
    }
        
    /*
     * function to add new knowledge
     */
    function add_knowledge($params)
    {
        $this->db->insert('knowledge',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update knowledge
     */
    function update_knowledge($Know_Id,$params)
    {
        $this->db->where('Know_Id',$Know_Id);
        return $this->db->update('knowledge',$params);
    }
    
    /*
     * function to delete knowledge
     */
    function delete_knowledge($Know_Id)
    {
        return $this->db->delete('knowledge',array('Know_Id'=>$Know_Id));
    }
}
