<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Suggestion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get suggestion by Sug_Id
     */
    function get_suggestion($Sug_Id)
    {
        return $this->db->get_where('suggestion',array('Sug_Id'=>$Sug_Id))->row_array();
    }
        
    /*
     * Get all suggestion
     */
    function get_all_suggestion()
    {
        $this->db->order_by('Sug_Id', 'desc');
        return $this->db->get('suggestion')->result_array();
    }
        
    /*
     * function to add new suggestion
     */
    function add_suggestion($params)
    {
        $this->db->insert('suggestion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update suggestion
     */
    function update_suggestion($Sug_Id,$params)
    {
        $this->db->where('Sug_Id',$Sug_Id);
        return $this->db->update('suggestion',$params);
    }
    
    /*
     * function to delete suggestion
     */
    function delete_suggestion($Sug_Id)
    {
        return $this->db->delete('suggestion',array('Sug_Id'=>$Sug_Id));
    }
}
