<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tacking_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tacking by tac_id
     */
    function get_tacking($tac_id)
    {
        return $this->db->get_where('tacking',array('tac_id'=>$tac_id))->row_array();
    }
        
    /*
     * Get all tacking
     */
    function get_all_tacking()
    {
        $this->db->order_by('tac_id', 'desc');
        return $this->db->get('tacking')->result_array();
    }
        
    /*
     * function to add new tacking
     */
    function add_tacking($params)
    {
        $this->db->insert('tacking',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tacking
     */
    function update_tacking($tac_id,$params)
    {
        $this->db->where('tac_id',$tac_id);
        return $this->db->update('tacking',$params);
    }
    
    /*
     * function to delete tacking
     */
    function delete_tacking($tac_id)
    {
        return $this->db->delete('tacking',array('tac_id'=>$tac_id));
    }
}
